name: Activity type
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*' # dev-new dev-this-new
      - 'feature/**' # feat/new feature/new/button
  workflow_dispatch:
  push:
    branches: #filter
      - main
      - 'dev-*' # dev-new dev-this-new
      - 'feature/**' # feat/new feature/new/button
    paths-ignore: #filter
      - ".github/workflows/*"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deployment
        run: echo "Deploying..."
