name: Deployment with lint and test
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deployment
        run: echo "Deploying..."
